/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.github.akboyd88.server;


import com.github.akboyd88.components.AppComponent;
import com.github.akboyd88.components.DaggerAppComponent;
import com.github.akboyd88.services.EchoService;
import com.github.akboyd88.services.MultiplyService;

import javax.inject.Inject;
import java.io.IOException;

public class App {

    private final TemplateServiceServerImpl server;

    @Inject
    public App(MultiplyService multiplyService, EchoService echoService){
        server = new TemplateServiceServerImpl(new TemplateServiceImpl(echoService, multiplyService));
    }

    public void start() throws IOException {
        server.start();
    }

    public void waitTillShutdown() throws InterruptedException {
        server.blockUntilShutdown();
    }

    public static void main(String[] args) throws IOException, InterruptedException {
        final App app = DaggerAppComponent.builder()
                .build().app();
        app.start();
        app.waitTillShutdown();
    }
}
